services:
  elasticsearch:
    image: elasticsearch:8.16.3
    container_name: elasticsearch_app
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false  # не используем аутентификацию и авторизацию
      - xpack.security.http.ssl.enabled=false
      - cluster.name=online_cinema_cluster
      - node.name=online_cinema
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m" # ограничиваем по памяти
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:9200/_cluster/health | grep -q '\"status\":\"green\"'"]
      interval: 10s
      retries: 5
      start_period: 20s
      timeout: 5s

  online_cinema:
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile
    container_name: online_cinema
    ports:
      - "8000:8000"
    depends_on:
      elasticsearch:
        condition: service_healthy
    volumes:
      - .:/usr/src/online_cinema
    env_file:
      - .env

volumes:
  es_data: